[package]
name = "mqtt3"
version = "0.1.0"
authors = ["Azure IoT Edge Devs"]
license = "MIT"
edition = "2018"

[dependencies]
bytes = "0.6"
serde = { version = "1.0", optional = true, features = ["derive"] }
tokio-util = { version = "0.5", features = ["full"] }


[features]
serde1 = ["serde"]